### ISSUE TITLE
Which version of drush is this?

### ISSUE THREAD

**Issue by dagomar** [mikebell/drush-docset#7]
I couldn't find this anywhere, maybe I didn't look hard enough :)

**Comment by mikebell** [comment]
It'll be a very old version, I'll try and update the docset today and then push it to Dash. This week I'll build a new Jenkins job to create a new release every week so I don't have to do it manually.

As for version numbers I've never included them in the front html but they should be visible in the composer.lock file.

**Comment by mikebell** [comment]
Updated drush version pending - https://github.com/Kapeli/Dash-User-Contributions/pull/890
